import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-950 text-slate-100">
      {/* Main Content */}
      <main className="mx-auto max-w-5xl px-4 py-10 md:py-14">
        <section className="rounded-xl bg-slate-900/60 p-6 md:p-10 shadow-2xl backdrop-blur ring-1 ring-cyan-300/10">
          <h1 className="mb-8 text-center text-3xl md:text-4xl font-bold text-cyan-300 drop-shadow">
            Terms &amp; Conditions
          </h1>

          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            This document is an electronic record in terms of Information
            Technology Act, 2000 and rules there under as applicable and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>

          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediaries guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of domain name{" "}
            <a href="https://www.infoziant.com" className="font-semibold text-cyan-300">www.infoziant.com</a>{" "}
            (&apos;Website&apos;), including the related mobile site and mobile
            application (hereinafter referred to as &apos;Platform&apos;).
          </p>

          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            The Platform is owned by{" "}
            <span className="font-semibold text-cyan-300">
              Calebinfoziant OPC private limited
            </span>
            , a company incorporated under the Companies Act, 1956 with its
            registered office at D401, Elcot Avenue, Saidapet Central Part West,
            Chennai, India (hereinafter referred to as &quot;Platform Owner&quot;,
            &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
          </p>

          <h2 className="mt-6 mb-4 border-b-2 border-cyan-300/40 pb-3 text-xl md:text-2xl font-semibold text-cyan-300">
            Agreement to Terms
          </h2>
          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            Your use of the Platform and services and tools are governed by the
            following terms and conditions (&quot;Terms of Use&quot;) as
            applicable to the Platform including the applicable policies which
            are incorporated herein by way of reference. If You transact on the
            Platform, You shall be subject to the policies that are applicable
            to the Platform for such transaction. By mere use of the Platform,
            You shall be contracting with the Platform Owner and these terms and
            conditions including the policies constitute Your binding
            obligations, with Platform Owner.
          </p>

          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            These Terms of Use relate to your use of our website, goods or
            services (collectively, &apos;Services&apos;). Any terms and
            conditions proposed by You which are in addition to or which
            conflict with these Terms of Use are expressly rejected by the
            Platform Owner and shall be of no force or effect. These Terms of
            Use can be modified at any time without assigning any reason. It is
            your responsibility to periodically review these Terms of Use to
            stay informed of updates.
          </p>

          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            For the purpose of these Terms of Use, wherever the context so
            requires &quot;you&quot;, &apos;your&apos; or &quot;user&quot; shall
            mean any natural or legal person who has agreed to become a
            user/buyer on the Platform.
          </p>

          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            <strong className="font-semibold text-cyan-200">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
              AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF
              USE.
            </strong>
          </p>

          <h2 className="mt-6 mb-4 border-b-2 border-cyan-300/40 pb-3 text-xl md:text-2xl font-semibold text-cyan-300">
            Terms of Use
          </h2>
          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            The use of Platform and/or availing of our Services is subject to
            the following Terms of Use:
          </p>

          <ul className="mb-6 ml-6 list-disc space-y-3 text-slate-300 text-sm md:text-base">
            <li>
              To access and use the Services, you agree to provide true, accurate
              and complete information to us during and after registration, and
              you shall be responsible for all acts done through the use of your
              registered account on the Platform.
            </li>
            <li>
              Neither we nor any third parties provide any warranty or guarantee
              as to the accuracy, timeliness, performance, completeness or
              suitability of the information and materials offered on this
              website or through the Services. You acknowledge these may contain
              inaccuracies or errors.
            </li>
            <li>
              Your use of our Services and the Platform is entirely at your own
              risk and discretion.
            </li>
            <li>
              The contents of the Platform and the Services are proprietary to
              us. You will not claim any intellectual property rights, title, or
              interest in the contents.
            </li>
            <li>
              Unauthorized use of the Platform and/or the Services may lead to
              action as per these Terms of Use and/or applicable laws.
            </li>
            <li>
              You agree to pay the charges associated with availing the Services.
            </li>
            <li>
              You agree not to use the Platform and/or Services for any unlawful
              or forbidden purpose.
            </li>
            <li>
              The Platform may contain links to third-party websites. You will
              be governed by their policies upon accessing those links.
            </li>
            <li>
              Initiating a transaction for availing the Services constitutes a
              legally binding contract with the Platform Owner.
            </li>
          </ul>

          <h2 className="mt-6 mb-4 border-b-2 border-cyan-300/40 pb-3 text-xl md:text-2xl font-semibold text-cyan-300">
            Indemnification
          </h2>
          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            You shall indemnify and hold harmless Platform Owner and its
            affiliates from any claim, demand, or penalty arising out of your
            breach of these Terms or violation of any law.
          </p>

          <h2 className="mt-6 mb-4 border-b-2 border-cyan-300/40 pb-3 text-xl md:text-2xl font-semibold text-cyan-300">
            Force Majeure
          </h2>
          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            The parties shall not be liable for any failure to perform an
            obligation under these Terms if performance is prevented by a force
            majeure event.
          </p>

          <h2 className="mt-6 mb-4 border-b-2 border-cyan-300/40 pb-3 text-xl md:text-2xl font-semibold text-cyan-300">
            Governing Law and Jurisdiction
          </h2>
          <p className="mb-2 text-slate-300 text-sm md:text-base text-justify">
            These Terms shall be governed by the laws of India.
          </p>
          <p className="mb-4 text-slate-300 text-sm md:text-base text-justify">
            All disputes shall be subject to the exclusive jurisdiction of the
            courts in{" "}
            <span className="font-semibold text-cyan-300">
              Chennai and Tamil Nadu
            </span>
            .
          </p>

          <h2 className="mt-6 mb-4 border-b-2 border-cyan-300/40 pb-3 text-xl md:text-2xl font-semibold text-cyan-300">
            Contact Information
          </h2>
          <p className="mb-2 text-slate-300 text-sm md:text-base text-justify">
            All concerns or communications must be sent using the contact
            information provided on this website.
          </p>
        </section>
      </main>
    </div>
  );
};

export default TermsAndConditions;
